export const mockedTasks = [
    {
      "id": 1,
      "title": "test",
      "description": "text",
      "image": "sarah-lachise-SIX-q58-UMo-unsplash.jpg",
      "letters": "a b c",
      "default_timer_min": 2,
      "default_timer_sec": 2,
      "bonus_timer_3_letters": 2,
      "bonus_timer_4_letters": 2,
      "bonus_timer_5_letters": 2,
      "bonus_timer_6_plus_letters": 2,
      "created_at": null,
      "publish_date": null
    },
    {
      "id": 2,
      "title": "test2",
      "description": "test2",
      "image": "jaeyoung-geoffrey-kang-0bi-a4YDWXY-unsplash.jpg",
      "letters": "p p p ",
      "default_timer_min": 5,
      "default_timer_sec": 0,
      "bonus_timer_3_letters": 5,
      "bonus_timer_4_letters": 5,
      "bonus_timer_5_letters": 5,
      "bonus_timer_6_plus_letters": 10,
      "created_at": null,
      "publish_date": null
    },
    {
      "id": 3,
      "title": "test2",
      "description": "test2",
      "image": "jaeyoung-geoffrey-kang-0bi-a4YDWXY-unsplash.jpg",
      "letters": "p p p ",
      "default_timer_min": 5,
      "default_timer_sec": 0,
      "bonus_timer_3_letters": 5,
      "bonus_timer_4_letters": 5,
      "bonus_timer_5_letters": 5,
      "bonus_timer_6_plus_letters": 10,
      "created_at": null,
      "publish_date": null
    },
    {
      "id": 4,
      "title": "test2",
      "description": "test2",
      "image": "jaeyoung-geoffrey-kang-0bi-a4YDWXY-unsplash.jpg",
      "letters": "p p p ",
      "default_timer_min": 5,
      "default_timer_sec": 0,
      "bonus_timer_3_letters": 5,
      "bonus_timer_4_letters": 5,
      "bonus_timer_5_letters": 5,
      "bonus_timer_6_plus_letters": 10,
      "created_at": null,
      "publish_date": null
    },
    {
      "id": 5,
      "title": "test2",
      "description": "test2",
      "image": "jaeyoung-geoffrey-kang-0bi-a4YDWXY-unsplash.jpg",
      "letters": "p p p ",
      "default_timer_min": 5,
      "default_timer_sec": 0,
      "bonus_timer_3_letters": 5,
      "bonus_timer_4_letters": 5,
      "bonus_timer_5_letters": 5,
      "bonus_timer_6_plus_letters": 10,
      "created_at": null,
      "publish_date": null
    }
  ]